### ISSUE TITLE
iCloud Bypass Discuss3 

### ISSUE THREAD

**Issue by Assasin0** [carcabot/iCloud-Bypass#13]

**Comment by Assasin0** [comment]
Hallo

**Comment by Ryahuman** [comment]
#12 deleted? why?

**Comment by csommers** [comment]
Obama did it

**Comment by Assasin0** [comment]
I do not know, but I opened it new

**Comment by 38aytac38** [comment]
![schermafbeelding 2014-10-14 om 01 06 19](https://cloud.githubusercontent.com/assets/392226/4621598/c1be2224-532d-11e4-9b9b-d0227dcf8216.png)

**Comment by Ryahuman** [comment]
strange..,thanks for opening another!

**Comment by khiiiyproject** [comment]
lol

**Comment by Assasin0** [comment]
@Faroukdot you are here ?

**Comment by MrPerita** [comment]
is everyone here

**Comment by ghost** [comment]
:/ now the old discussion is lost?

**Comment by leycoder** [comment]
wath hpn

**Comment by MrPerita** [comment]
someone closed the issue

**Comment by 38aytac38** [comment]
to much comments it exceeded 2500

**Comment by Faroukd0t** [comment]
@Assasin0 yep ^^

**Comment by Faroukd0t** [comment]
it's simple to do with XAMPP... i will upload my folder htdocs and put the link here

edit : http://www.4shared.com/zip/7JxsEUABce/htdocs.html

**Comment by well0nez** [comment]
Oh man, i see it coming.... in 2 Days is this Topic also closed because of this.
Let the Dev's doing their jobs. Why nobody is opening a little chat or some setup some forum, that you can chat and test it seperatly.... this here is a developers platform, not a forum...
Please think about it. i dont mean this offensive, but what the most of you do (which dont have any clue about what they're doing) is time waisting.....
So let the devs be devs and let them do their job, and you keep and be patient.

Because you will never get it run without an exploit, some hole or the new working signed keys.
You can setup an xampp or anything you want, you dont get it to work with public stuff.
Please think about this!

**Comment by Faroukd0t** [comment]
well0nez how to learn properly without being in contact with some developers and follow their advice ?

**Comment by Assasin0** [comment]
@Faroukdot thank you :+1:

**Comment by well0nez** [comment]
The most (i dont speak for everything) people are not here for learning something, they are here to get a bypass. Thats ok, but this is the 3rd topic which is full spammed by people which are dont know what they are exactly doing and keep begging.  I dont want you to leave and dont get the information you need. i just want to give you the advice that all these public servers (include xampp stuff) dont work anymore, and that you can't fix it by trying hard. you need more informations, which the devs dont want share.. so its really pointless you know. i mean it not offensive, its just that i've seen all threads beeing spammed in just a few days, you loose the overview.  Everybody has something to say or to ask, but they are all getting to the same result: no bypass and more questions.
I' mean its nice that some people want to learn something and want to advance their knowing about bypassing or apple's activation process and thats okay, but i dont think that this here is'nt the right platform. thats all i'm saying.

**Comment by Faroukd0t** [comment]
well, you did not say anything wrong, I respect your point of view.

**Comment by khiiiyproject** [comment]
WTF CASE CLOSED

**Comment by Mocartxx** [comment]
any progress, beta with no UDID don't working

**Comment by TTMTT** [comment]
## discuss3:

## https://github.com/carcabot/iCloud-Bypass/issues/14
