### ISSUE TITLE
Several Questions

### ISSUE THREAD

**Issue by yansama** [carcabot/iCloud-Bypass#15]
1 - How the Server Method work?
2 - Is there a possible way to exploit iOs 7 files without Jailbreak?
3 - What's so different about the iPhone 4 to get exploited easly (I wasn't quit convinced by the A4 theory)
4 - How Activation work?

**Comment by sniperegy** [comment]
How ?

**Comment by yansama** [comment]
Yeah How?

**Comment by Beyond4mazing** [comment]
Ok listen here, the DeviceCertificate is given to the device by the apple server which means that the apple private key can decrypt the sent activation_info from iTunes.
So the process goes like this, iTunes generates Activation Request and encrypts it with device public key, apple server decrypts the request with the private key and reads info compares with db and generates activation ticket.
So far we can intercept the Activation Request but we can not edit the data because that would mess up the encryption on both sides and you get activation information is invalid.

**Comment by yansama** [comment]
Clear as Crystal !
